# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sim_api import SimApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSimApi(unittest.TestCase):
    """SimApi unit test stubs"""

    def setUp(self):
        self.api = SimApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_annotation_score(self):
        """Test case for get_annotation_score

        Get annotation score  # noqa: E501
        """
        pass

    def test_get_sim_compare(self):
        """Test case for get_sim_compare

        Compare a reference profile vs one profiles  # noqa: E501
        """
        pass

    def test_get_sim_search(self):
        """Test case for get_sim_search

        Search for phenotypically similar diseases or model genes  # noqa: E501
        """
        pass

    def test_post_annotation_score(self):
        """Test case for post_annotation_score

        Get annotation score  # noqa: E501
        """
        pass

    def test_post_sim_compare(self):
        """Test case for post_sim_compare

        Compare a reference profile vs one or more profiles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
