# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.variationset_api import VariationsetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVariationsetApi(unittest.TestCase):
    """VariationsetApi unit test stubs"""

    def setUp(self):
        self.api = VariationsetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_variant_set_item(self):
        """Test case for delete_variant_set_item

        Deletes variant set  # noqa: E501
        """
        pass

    def test_get_variant_analyze(self):
        """Test case for get_variant_analyze

        Returns list of matches  # noqa: E501
        """
        pass

    def test_get_variant_set_item(self):
        """Test case for get_variant_set_item

        Returns a variant set  # noqa: E501
        """
        pass

    def test_get_variant_sets_archive_collection(self):
        """Test case for get_variant_sets_archive_collection

        Returns list of variant sets from a specified time period  # noqa: E501
        """
        pass

    def test_get_variant_sets_collection(self):
        """Test case for get_variant_sets_collection

        Returns list of variant sets  # noqa: E501
        """
        pass

    def test_post_variant_sets_collection(self):
        """Test case for post_variant_sets_collection

        Creates a new variant set  # noqa: E501
        """
        pass

    def test_put_variant_set_item(self):
        """Test case for put_variant_set_item

        Updates a variant set  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
