# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mme_api import MmeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMmeApi(unittest.TestCase):
    """MmeApi unit test stubs"""

    def setUp(self):
        self.api = MmeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_disease_mme(self):
        """Test case for post_disease_mme

        Match a patient to diseases based on their phenotypes  # noqa: E501
        """
        pass

    def test_post_fly_mme(self):
        """Test case for post_fly_mme

        Match a patient to fruit fly genes based on similar phenotypes  # noqa: E501
        """
        pass

    def test_post_mouse_mme(self):
        """Test case for post_mouse_mme

        Match a patient to mouse genes based on similar phenotypes  # noqa: E501
        """
        pass

    def test_post_nematode_mme(self):
        """Test case for post_nematode_mme

        Match a patient to nematode genes based on similar phenotypes  # noqa: E501
        """
        pass

    def test_post_zebrafish_mme(self):
        """Test case for post_zebrafish_mme

        Match a patient to zebrafish genes based on similar phenotypes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
