# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.nlpannotate_api import NlpannotateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNlpannotateApi(unittest.TestCase):
    """NlpannotateApi unit test stubs"""

    def setUp(self):
        self.api = NlpannotateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_annotate(self):
        """Test case for get_annotate

        Annotate a given text using SciGraph annotator  # noqa: E501
        """
        pass

    def test_get_annotate_entities(self):
        """Test case for get_annotate_entities

        Annotate a given content using SciGraph annotator and get all entities from content  # noqa: E501
        """
        pass

    def test_post_annotate(self):
        """Test case for post_annotate

        Annotate a given text using SciGraph annotator  # noqa: E501
        """
        pass

    def test_post_annotate_entities(self):
        """Test case for post_annotate_entities

        Annotate a given content using SciGraph annotator and get all entities from content  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
