# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cam_api import CamApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCamApi(unittest.TestCase):
    """CamApi unit test stubs"""

    def setUp(self):
        self.api = CamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_activity_collection(self):
        """Test case for get_activity_collection

        Returns list of models  # noqa: E501
        """
        pass

    def test_get_instance_object(self):
        """Test case for get_instance_object

        Returns list of matches  # noqa: E501
        """
        pass

    def test_get_model_collection(self):
        """Test case for get_model_collection

        Returns list of ALL models  # noqa: E501
        """
        pass

    def test_get_model_contributors(self):
        """Test case for get_model_contributors

        Returns list of all contributors across all models  # noqa: E501
        """
        pass

    def test_get_model_instances(self):
        """Test case for get_model_instances

        Returns list of all instances  # noqa: E501
        """
        pass

    def test_get_model_object(self):
        """Test case for get_model_object

        Returns a complete model  # noqa: E501
        """
        pass

    def test_get_model_properties(self):
        """Test case for get_model_properties

        Returns list of all properties used across all models  # noqa: E501
        """
        pass

    def test_get_model_property_values(self):
        """Test case for get_model_property_values

        Returns list property-values for all models  # noqa: E501
        """
        pass

    def test_get_model_query(self):
        """Test case for get_model_query

        Returns list of models matching query  # noqa: E501
        """
        pass

    def test_get_physical_interaction(self):
        """Test case for get_physical_interaction

        Returns list of models  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
