# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mart_api import MartApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMartApi(unittest.TestCase):
    """MartApi unit test stubs"""

    def setUp(self):
        self.api = MartApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mart_case_associations_resource(self):
        """Test case for get_mart_case_associations_resource

        Bulk download of case associations  # noqa: E501
        """
        pass

    def test_get_mart_disease_associations_resource(self):
        """Test case for get_mart_disease_associations_resource

        Bulk download of disease associations  # noqa: E501
        """
        pass

    def test_get_mart_gene_associations_resource(self):
        """Test case for get_mart_gene_associations_resource

        Bulk download of gene associations  # noqa: E501
        """
        pass

    def test_get_mart_ortholog_associations_resource(self):
        """Test case for get_mart_ortholog_associations_resource

        Bulk download of orthologs  # noqa: E501
        """
        pass

    def test_get_mart_paralog_associations_resource(self):
        """Test case for get_mart_paralog_associations_resource

        Bulk download of paralogs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
