# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_api import SearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_autocomplete(self):
        """Test case for get_autocomplete

        Returns list of matching concepts or entities using lexical search  # noqa: E501
        """
        pass

    def test_get_search_entities(self):
        """Test case for get_search_entities

        Returns list of matching concepts or entities using lexical search  # noqa: E501
        """
        pass

    def test_get_search_hpo_entities(self):
        """Test case for get_search_hpo_entities

        Returns list of matching concepts or entities using lexical search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
