# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.compare_input import CompareInput  # noqa: E501
from swagger_client.rest import ApiException


class TestCompareInput(unittest.TestCase):
    """CompareInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompareInput(self):
        """Test CompareInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.compare_input.CompareInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
