# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bioentitysetslimmer_api import BioentitysetslimmerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBioentitysetslimmerApi(unittest.TestCase):
    """BioentitysetslimmerApi unit test stubs"""

    def setUp(self):
        self.api = BioentitysetslimmerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity_set_anatomy_slimmer(self):
        """Test case for get_entity_set_anatomy_slimmer

        For a given gene(s), summarize its annotations over a defined set of slim  # noqa: E501
        """
        pass

    def test_get_entity_set_function_slimmer(self):
        """Test case for get_entity_set_function_slimmer

        For a given gene(s), summarize its annotations over a defined set of slim  # noqa: E501
        """
        pass

    def test_get_entity_set_phenotype_slimmer(self):
        """Test case for get_entity_set_phenotype_slimmer

        For a given gene(s), summarize its annotations over a defined set of slim  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
