# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ontology_api import OntologyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOntologyApi(unittest.TestCase):
    """OntologyApi unit test stubs"""

    def setUp(self):
        self.api = OntologyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ontology_subset(self):
        """Test case for get_ontology_subset

        Returns meta data of an ontology subset (slim)  # noqa: E501
        """
        pass

    def test_get_ontology_term(self):
        """Test case for get_ontology_term

        Returns meta data of an ontology term  # noqa: E501
        """
        pass

    def test_get_ontology_term_graph(self):
        """Test case for get_ontology_term_graph

        Returns graph of an ontology term  # noqa: E501
        """
        pass

    def test_get_ontology_term_subgraph(self):
        """Test case for get_ontology_term_subgraph

        Extract a subgraph from an ontology term  # noqa: E501
        """
        pass

    def test_get_ontology_term_subsets(self):
        """Test case for get_ontology_term_subsets

        Returns subsets (slims) associated to an ontology term  # noqa: E501
        """
        pass

    def test_get_ontology_terms_shared_ancestor(self):
        """Test case for get_ontology_terms_shared_ancestor

        Returns the ancestor ontology terms shared by two ontology terms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
