# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.owlontology_api import OwlontologyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOwlontologyApi(unittest.TestCase):
    """OwlontologyApi unit test stubs"""

    def setUp(self):
        self.api = OwlontologyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_dl_query(self):
        """Test case for get_dl_query

        Placeholder - use OWLery for now  # noqa: E501
        """
        pass

    def test_get_sparql_query(self):
        """Test case for get_sparql_query

        Placeholder - use direct SPARQL endpoint for now  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
