# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompareInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reference_ids': 'list[str]',
        'query_ids': 'list[list[str]]'
    }

    attribute_map = {
        'reference_ids': 'reference_ids',
        'query_ids': 'query_ids'
    }

    def __init__(self, reference_ids=None, query_ids=None):  # noqa: E501
        """CompareInput - a model defined in Swagger"""  # noqa: E501
        self._reference_ids = None
        self._query_ids = None
        self.discriminator = None
        if reference_ids is not None:
            self.reference_ids = reference_ids
        if query_ids is not None:
            self.query_ids = query_ids

    @property
    def reference_ids(self):
        """Gets the reference_ids of this CompareInput.  # noqa: E501

        list of ids  # noqa: E501

        :return: The reference_ids of this CompareInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._reference_ids

    @reference_ids.setter
    def reference_ids(self, reference_ids):
        """Sets the reference_ids of this CompareInput.

        list of ids  # noqa: E501

        :param reference_ids: The reference_ids of this CompareInput.  # noqa: E501
        :type: list[str]
        """

        self._reference_ids = reference_ids

    @property
    def query_ids(self):
        """Gets the query_ids of this CompareInput.  # noqa: E501

        list of query profiles  # noqa: E501

        :return: The query_ids of this CompareInput.  # noqa: E501
        :rtype: list[list[str]]
        """
        return self._query_ids

    @query_ids.setter
    def query_ids(self, query_ids):
        """Sets the query_ids of this CompareInput.

        list of query profiles  # noqa: E501

        :param query_ids: The query_ids of this CompareInput.  # noqa: E501
        :type: list[list[str]]
        """

        self._query_ids = query_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompareInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompareInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
