# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.association import Association  # noqa: F401,E501

class D2PAssociation(Association):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'frequency': 'object',
        'onset': 'object'
    }
    if hasattr(Association, "swagger_types"):
        swagger_types.update(Association.swagger_types)

    attribute_map = {
        'frequency': 'frequency',
        'onset': 'onset'
    }
    if hasattr(Association, "attribute_map"):
        attribute_map.update(Association.attribute_map)

    def __init__(self, frequency=None, onset=None, *args, **kwargs):  # noqa: E501
        """D2PAssociation - a model defined in Swagger"""  # noqa: E501
        self._frequency = None
        self._onset = None
        self.discriminator = None
        if frequency is not None:
            self.frequency = frequency
        if onset is not None:
            self.onset = onset
        Association.__init__(self, *args, **kwargs)

    @property
    def frequency(self):
        """Gets the frequency of this D2PAssociation.  # noqa: E501

        Frequency of phenotype in patients with disease  # noqa: E501

        :return: The frequency of this D2PAssociation.  # noqa: E501
        :rtype: object
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this D2PAssociation.

        Frequency of phenotype in patients with disease  # noqa: E501

        :param frequency: The frequency of this D2PAssociation.  # noqa: E501
        :type: object
        """

        self._frequency = frequency

    @property
    def onset(self):
        """Gets the onset of this D2PAssociation.  # noqa: E501

        Onset of phenotype in disease process  # noqa: E501

        :return: The onset of this D2PAssociation.  # noqa: E501
        :rtype: object
        """
        return self._onset

    @onset.setter
    def onset(self, onset):
        """Sets the onset of this D2PAssociation.

        Onset of phenotype in disease process  # noqa: E501

        :param onset: The onset of this D2PAssociation.  # noqa: E501
        :type: object
        """

        self._onset = onset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(D2PAssociation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, D2PAssociation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
