# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Feature(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'label': 'str',
        'type': 'str',
        'is_present': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'label': 'label',
        'type': 'type',
        'is_present': 'isPresent'
    }

    def __init__(self, id=None, label=None, type=None, is_present=None):  # noqa: E501
        """Feature - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._label = None
        self._type = None
        self._is_present = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        if type is not None:
            self.type = type
        if is_present is not None:
            self.is_present = is_present

    @property
    def id(self):
        """Gets the id of this Feature.  # noqa: E501

        curie formatted id  # noqa: E501

        :return: The id of this Feature.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Feature.

        curie formatted id  # noqa: E501

        :param id: The id of this Feature.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this Feature.  # noqa: E501

        curie formatted id  # noqa: E501

        :return: The label of this Feature.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Feature.

        curie formatted id  # noqa: E501

        :param label: The label of this Feature.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this Feature.  # noqa: E501

        feature type (only phenotype supported)  # noqa: E501

        :return: The type of this Feature.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Feature.

        feature type (only phenotype supported)  # noqa: E501

        :param type: The type of this Feature.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def is_present(self):
        """Gets the is_present of this Feature.  # noqa: E501

        is the feature present  # noqa: E501

        :return: The is_present of this Feature.  # noqa: E501
        :rtype: bool
        """
        return self._is_present

    @is_present.setter
    def is_present(self, is_present):
        """Sets the is_present of this Feature.

        is the feature present  # noqa: E501

        :param is_present: The is_present of this Feature.  # noqa: E501
        :type: bool
        """

        self._is_present = is_present

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Feature, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Feature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
