# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LayAutocomplete(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'label': 'str',
        'matched_synonym': 'str',
        'highlight': 'str'
    }

    attribute_map = {
        'id': 'id',
        'label': 'label',
        'matched_synonym': 'matched_synonym',
        'highlight': 'highlight'
    }

    def __init__(self, id=None, label=None, matched_synonym=None, highlight=None):  # noqa: E501
        """LayAutocomplete - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._label = None
        self._matched_synonym = None
        self._highlight = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        if matched_synonym is not None:
            self.matched_synonym = matched_synonym
        if highlight is not None:
            self.highlight = highlight

    @property
    def id(self):
        """Gets the id of this LayAutocomplete.  # noqa: E501

        curie formatted id  # noqa: E501

        :return: The id of this LayAutocomplete.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LayAutocomplete.

        curie formatted id  # noqa: E501

        :param id: The id of this LayAutocomplete.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this LayAutocomplete.  # noqa: E501

        primary label (rdfs:label)  # noqa: E501

        :return: The label of this LayAutocomplete.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this LayAutocomplete.

        primary label (rdfs:label)  # noqa: E501

        :param label: The label of this LayAutocomplete.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def matched_synonym(self):
        """Gets the matched_synonym of this LayAutocomplete.  # noqa: E501

        matched synonym  # noqa: E501

        :return: The matched_synonym of this LayAutocomplete.  # noqa: E501
        :rtype: str
        """
        return self._matched_synonym

    @matched_synonym.setter
    def matched_synonym(self, matched_synonym):
        """Sets the matched_synonym of this LayAutocomplete.

        matched synonym  # noqa: E501

        :param matched_synonym: The matched_synonym of this LayAutocomplete.  # noqa: E501
        :type: str
        """

        self._matched_synonym = matched_synonym

    @property
    def highlight(self):
        """Gets the highlight of this LayAutocomplete.  # noqa: E501

        solr highlight  # noqa: E501

        :return: The highlight of this LayAutocomplete.  # noqa: E501
        :rtype: str
        """
        return self._highlight

    @highlight.setter
    def highlight(self, highlight):
        """Sets the highlight of this LayAutocomplete.

        solr highlight  # noqa: E501

        :param highlight: The highlight of this LayAutocomplete.  # noqa: E501
        :type: str
        """

        self._highlight = highlight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LayAutocomplete, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LayAutocomplete):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
