# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Span(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'int',
        'end': 'int',
        'text': 'str',
        'token': 'list[Token]'
    }

    attribute_map = {
        'start': 'start',
        'end': 'end',
        'text': 'text',
        'token': 'token'
    }

    def __init__(self, start=None, end=None, text=None, token=None):  # noqa: E501
        """Span - a model defined in Swagger"""  # noqa: E501
        self._start = None
        self._end = None
        self._text = None
        self._token = None
        self.discriminator = None
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end
        if text is not None:
            self.text = text
        if token is not None:
            self.token = token

    @property
    def start(self):
        """Gets the start of this Span.  # noqa: E501

        start of span text relative to content  # noqa: E501

        :return: The start of this Span.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this Span.

        start of span text relative to content  # noqa: E501

        :param start: The start of this Span.  # noqa: E501
        :type: int
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this Span.  # noqa: E501

        end of span text relative to content  # noqa: E501

        :return: The end of this Span.  # noqa: E501
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Span.

        end of span text relative to content  # noqa: E501

        :param end: The end of this Span.  # noqa: E501
        :type: int
        """

        self._end = end

    @property
    def text(self):
        """Gets the text of this Span.  # noqa: E501

        span text  # noqa: E501

        :return: The text of this Span.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Span.

        span text  # noqa: E501

        :param text: The text of this Span.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def token(self):
        """Gets the token of this Span.  # noqa: E501

        A token or entity extracted from the span text  # noqa: E501

        :return: The token of this Span.  # noqa: E501
        :rtype: list[Token]
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Span.

        A token or entity extracted from the span text  # noqa: E501

        :param token: The token of this Span.  # noqa: E501
        :type: list[Token]
        """

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Span, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Span):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
