# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SufficiencyPostInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'features': 'list[Feature]'
    }

    attribute_map = {
        'id': 'id',
        'features': 'features'
    }

    def __init__(self, id=None, features=None):  # noqa: E501
        """SufficiencyPostInput - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._features = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if features is not None:
            self.features = features

    @property
    def id(self):
        """Gets the id of this SufficiencyPostInput.  # noqa: E501

        curie formatted id  # noqa: E501

        :return: The id of this SufficiencyPostInput.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SufficiencyPostInput.

        curie formatted id  # noqa: E501

        :param id: The id of this SufficiencyPostInput.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def features(self):
        """Gets the features of this SufficiencyPostInput.  # noqa: E501

        list of features  # noqa: E501

        :return: The features of this SufficiencyPostInput.  # noqa: E501
        :rtype: list[Feature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this SufficiencyPostInput.

        list of features  # noqa: E501

        :param features: The features of this SufficiencyPostInput.  # noqa: E501
        :type: list[Feature]
        """

        self._features = features

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SufficiencyPostInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SufficiencyPostInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
