# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Token(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'categories': 'list[str]',
        'terms': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'categories': 'categories',
        'terms': 'terms'
    }

    def __init__(self, id=None, categories=None, terms=None):  # noqa: E501
        """Token - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._categories = None
        self._terms = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if categories is not None:
            self.categories = categories
        if terms is not None:
            self.terms = terms

    @property
    def id(self):
        """Gets the id of this Token.  # noqa: E501

        The CURIE for the entity or token  # noqa: E501

        :return: The id of this Token.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Token.

        The CURIE for the entity or token  # noqa: E501

        :param id: The id of this Token.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def categories(self):
        """Gets the categories of this Token.  # noqa: E501

        entity categories  # noqa: E501

        :return: The categories of this Token.  # noqa: E501
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this Token.

        entity categories  # noqa: E501

        :param categories: The categories of this Token.  # noqa: E501
        :type: list[str]
        """

        self._categories = categories

    @property
    def terms(self):
        """Gets the terms of this Token.  # noqa: E501

        terms  # noqa: E501

        :return: The terms of this Token.  # noqa: E501
        :rtype: list[str]
        """
        return self._terms

    @terms.setter
    def terms(self, terms):
        """Sets the terms of this Token.

        terms  # noqa: E501

        :param terms: The terms of this Token.  # noqa: E501
        :type: list[str]
        """

        self._terms = terms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Token, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Token):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
