# coding: utf-8

"""
    BioLink API

    API integration layer for linked biological objects.   __Source:__ https://github.com/biolink/biolink-api/  # noqa: E501

    OpenAPI spec version: 1.1.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class RelationusageApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_relation_usage_between_resource(self, subject_category, object_category, **kwargs):  # noqa: E501
        """All relations used plus count of associations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_between_resource(subject_category, object_category, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_category: (required)
        :param str object_category: (required)
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_relation_usage_between_resource_with_http_info(subject_category, object_category, **kwargs)  # noqa: E501
        else:
            (data) = self.get_relation_usage_between_resource_with_http_info(subject_category, object_category, **kwargs)  # noqa: E501
            return data

    def get_relation_usage_between_resource_with_http_info(self, subject_category, object_category, **kwargs):  # noqa: E501
        """All relations used plus count of associations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_between_resource_with_http_info(subject_category, object_category, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_category: (required)
        :param str object_category: (required)
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subject_category', 'object_category', 'subject_taxon', 'evidence']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_relation_usage_between_resource" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'subject_category' is set
        if ('subject_category' not in params or
                params['subject_category'] is None):
            raise ValueError("Missing the required parameter `subject_category` when calling `get_relation_usage_between_resource`")  # noqa: E501
        # verify the required parameter 'object_category' is set
        if ('object_category' not in params or
                params['object_category'] is None):
            raise ValueError("Missing the required parameter `object_category` when calling `get_relation_usage_between_resource`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'subject_category' in params:
            path_params['subject_category'] = params['subject_category']  # noqa: E501
        if 'object_category' in params:
            path_params['object_category'] = params['object_category']  # noqa: E501

        query_params = []
        if 'subject_taxon' in params:
            query_params.append(('subject_taxon', params['subject_taxon']))  # noqa: E501
        if 'evidence' in params:
            query_params.append(('evidence', params['evidence']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/relation/usage/between/{subject_category}/{object_category}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AssociationResults]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_relation_usage_pivot_label_resource(self, **kwargs):  # noqa: E501
        """Relation usage count for all subj x obj category combinations, showing label  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_pivot_label_resource(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_relation_usage_pivot_label_resource_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_relation_usage_pivot_label_resource_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_relation_usage_pivot_label_resource_with_http_info(self, **kwargs):  # noqa: E501
        """Relation usage count for all subj x obj category combinations, showing label  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_pivot_label_resource_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subject_taxon', 'evidence']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_relation_usage_pivot_label_resource" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subject_taxon' in params:
            query_params.append(('subject_taxon', params['subject_taxon']))  # noqa: E501
        if 'evidence' in params:
            query_params.append(('evidence', params['evidence']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/relation/usage/pivot/label', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AssociationResults]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_relation_usage_pivot_resource(self, **kwargs):  # noqa: E501
        """Relation usage count for all subj x obj category combinations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_pivot_resource(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_relation_usage_pivot_resource_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_relation_usage_pivot_resource_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_relation_usage_pivot_resource_with_http_info(self, **kwargs):  # noqa: E501
        """Relation usage count for all subj x obj category combinations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_pivot_resource_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subject_taxon', 'evidence']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_relation_usage_pivot_resource" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subject_taxon' in params:
            query_params.append(('subject_taxon', params['subject_taxon']))  # noqa: E501
        if 'evidence' in params:
            query_params.append(('evidence', params['evidence']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/relation/usage/pivot', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AssociationResults]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_relation_usage_resource(self, **kwargs):  # noqa: E501
        """All relations used plus count of associations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_resource(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_relation_usage_resource_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_relation_usage_resource_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_relation_usage_resource_with_http_info(self, **kwargs):  # noqa: E501
        """All relations used plus count of associations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_relation_usage_resource_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str subject_taxon: SUBJECT TAXON id, e.g. NCBITaxon:9606. Includes inferred by default
        :param str evidence: Object id, e.g. ECO:0000501 (for IEA; Includes inferred by default)                     or a specific publication or other supporting ibject, e.g. ZFIN:ZDB-PUB-060503-2.                     
        :return: list[AssociationResults]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['subject_taxon', 'evidence']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_relation_usage_resource" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'subject_taxon' in params:
            query_params.append(('subject_taxon', params['subject_taxon']))  # noqa: E501
        if 'evidence' in params:
            query_params.append(('evidence', params['evidence']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/relation/usage/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AssociationResults]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
